// brief.js — the intelligence layer.
// Turns a detected signal (diff result + history context) into a plain-language
// "what changed, what it means, what to do" report.
//
// Provider-agnostic, OpenAI-compatible chat API. Primary: Groq. Override the
// base URL/model via env if you prefer another OpenAI-compatible provider.
// Deterministic rule-based fallback if no API key or on error — the pipeline
// never hard-crashes on missing LLM access.

import "dotenv/config";

const BRIEF_MODEL = process.env.SENTINEL_MODEL || "llama-3.3-70b-versatile";
const BRIEF_BASE = process.env.SENTINEL_BASE_URL || "https://api.groq.com/openai/v1";
const BRIEF_KEY = process.env.SENTINEL_API_KEY || process.env.GROQ_API_KEY || "";

async function runLLM(system, user, { timeout = 45_000 } = {}) {
  if (!BRIEF_KEY) return { ok: false, error: "no API key (set SENTINEL_API_KEY or GROQ_API_KEY)" };
  const ctrl = new AbortController();
  const t = setTimeout(() => ctrl.abort(), timeout);
  try {
    const res = await fetch(`${BRIEF_BASE}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${BRIEF_KEY}`,
      },
      body: JSON.stringify({
        model: BRIEF_MODEL,
        temperature: 0.4,
        max_tokens: 300,
        messages: [
          { role: "system", content: system },
          { role: "user", content: user },
        ],
      }),
      signal: ctrl.signal,
    });
    clearTimeout(t);
    if (!res.ok) {
      const text = await res.text().catch(() => "");
      return { ok: false, error: `HTTP ${res.status}: ${text.slice(0, 300)}` };
    }
    const data = await res.json();
    const text = data?.choices?.[0]?.message?.content;
    return text ? { ok: true, text: text.trim() } : { ok: false, error: "empty response" };
  } catch (e) {
    clearTimeout(t);
    return { ok: false, error: e.message };
  }
}

/** Deterministic fallback brief — always available, never blocks. */
export function fallbackBrief(targetName, signal) {
  const lines = [];
  lines.push(`# Signal report — ${targetName}`);
  lines.push(``);
  lines.push(`Detected: **${signal.label}** (severity: ${signal.severity})`);
  lines.push(``);
  if (signal.reasons.length) {
    lines.push(`What changed:`);
    for (const r of signal.reasons) lines.push(`- ${r}`);
  } else {
    lines.push(`No material change to report.`);
  }
  lines.push(``);
  lines.push(`_Generated by SignalSentinel (deterministic mode). A GROQ_API_KEY is only needed for AI narratives._`);
  return lines.join("\n");
}

/**
 * Generate a narrative brief.
 * @param {object} ctx { targetName, signal, site, command, capturedAt, rows, history }
 */
export async function generateBrief(ctx) {
  const { targetName, signal, site, command, capturedAt, history } = ctx;

  if (!signal || signal.severity === "none") {
    return fallbackBrief(targetName, signal ?? { label: "no material change", severity: "none", reasons: [] });
  }

  const preview = (history || [])
    .slice(-6)
    .map((h) => `[${(h.capturedAt || "").slice(0, 19).replace("T", " ")}] healthy=${h.healthy} changed=${h.changed} sev=${h.severity}`)
    .join("\n");

  const system = `You are SignalSentinel, a competitor-intelligence analyst. Write short, concrete, useful briefs for a product manager. Do not invent facts. Max 150 words.`;

  const user = [
    `Target: ${targetName} (webcmd ${site} ${command})`,
    `Detected: ${signal.label}`,
    `Severity: ${signal.severity}`,
    `What changed:`,
    signal.reasons.map((r) => `  - ${r}`).join("\n"),
    ``,
    `Recent history:`,
    preview || "  (no prior history)",
    ``,
    `Write a brief in three sections:`,
    `1) What changed`,
    `2) What it likely means for the competitor/market`,
    `3) Suggested attention or next step`,
  ].join("\n");

  const res = await runLLM(system, user);
  if (res.ok && res.text) {
    return `# ${targetName} — brief (${(capturedAt || "").slice(0, 10)})\n\n${res.text}`;
  }
  // Fall back to the rule-based brief on any failure (missing key, network, 4xx/5xx).
  return fallbackBrief(targetName, signal);
}